import type { Metadata } from "next";
import { Rajdhani, Jersey_10_Charted as Sans } from "next/font/google";
import "./globals.css";
import { Contact } from "./components/contact";
import { Footer } from "./components/footer";
import { Header } from "./components/header";

const rajdhani = Rajdhani({
  subsets: ["latin"],
  display: "swap",
  weight: "400",
});

const sans = Sans({
  subsets: ["latin"],
  weight: "400",
  display: "swap",
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${rajdhani.className} ${sans.variable} text-white bg-[#215e4c]`}
      >
        <Header />
        {children}
        <Contact />
        <Footer />
      </body>
    </html>
  );
}
